auto:        true
server:      false
server_port: 4000
baseurl:    /

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    rdiscount
permalink:   /:year/:month/:day/:title

rdiscount:
  extensions: [smart]